server:
  port: 8080

telegram:
  messages:
    welcome: Salve! Ti ho registrato al bot, d'ora in poi quando ho da segnalarti qualcosa ti scrivero
    exit: Sei stato correttamente rimosso dal Bot! Ciao!
  commands:
    start: /start
    stop: /stop

binance:
  cache:
    max: 300
  interval: ONE_MINUTE #FIFTEEN_MINUTES
  coin: ETHBUSD