server:
  port: 8080

telegram:
  messages:
    welcome: Salve! Ti ho registrato al bot, d'ora in poi quando ho da segnalarti qualcosa ti scrivero
    exit: Sei stato correttamente rimosso dal Bot! Ciao!
    configuration: Ad ora sono configurato per rispondere ai comandi /start e /stop .
  commands:
    start: /start
    stop: /stop

binance:
  cache:
    max: 300
  pad%: 0.01
  interval: HALF_HOURLY #ONE_MINUTE #FIFTEEN_MINUTES #HOURLY #
  coin: ETHBUSD

firestore:
  collection:
    telegramuser: telegramUser